(in-package :squirl-demo)

(defclass planet-demo (demo)
  ((planet :initarg :planet :accessor planet))
  (:default-initargs :name "Planetary Gravity OMFG."))

(defmethod update-demo ((demo planet-demo) dt)
  (incf (accumulator demo) (if (> dt *dt-threshold*) *dt-threshold* dt))
  (loop while (>= (accumulator demo) (physics-timestep demo))
     do (world-step (world demo) (physics-timestep demo))
       (body-update-position (planet demo) (physics-timestep demo))
     (decf (accumulator demo) (physics-timestep demo))))

(defbody planetary-body)

(defmethod body-update-velocity ((body planetary-body) gravity damping dt)
  (declare (ignore gravity))
  (let* ((position (body-position body))
         (gravity (vec* position (/ -50000 (vec. position position)))))
    (call-next-method body gravity damping dt)))

(defun random-position (radius)
  (loop for vec = (vec (- (random (- 640 (* 2 radius)))
                          (- 320 radius))
                       (- (random (- 480 (* 2 radius)))
                          (- 240 radius)))
     when (< 88 (vec-length vec) 200)
     return vec))

(let ((size 10) (mass 1))
  (defun add-box ()
    (let* ((verts (list (vec (- size) (- size))
                        (vec (- size) size)
                        (vec size size)
                        (vec size (- size))))
           (body (make-planetary-body :mass mass :inertia (moment-for-poly mass verts)
                                      :position (random-position (vec-length (vec size size)))
                                      :velocity (vec* (angle->vec (* pi (random 2d0)))
                                                      (random 200d0)))))
      (attach-shape (make-poly verts :friction 0.7 :restitution 1) body)
      (world-add-body (world *current-demo*) body))))

(defmethod init-demo ((demo planet-demo))
  (let ((planet-body (make-body :angular-velocity 0.3 :actor :not-grabbable))
        (shape (make-circle 70 :restitution 1 :friction 0.8)))
    (attach-shape shape planet-body)
    (setf (planet demo) planet-body)
    (reset-shape-id-counter)
    (setf (world demo) (make-world :iterations 20))
    (loop repeat 22 do (add-box))
    (world-add-body (world demo) planet-body)
    (world demo)))

(pushnew 'planet-demo *demos*)
